stages:
  - test
  - deploy

test-backend:
  image: python:3.8-alpine
  stage: test
  script:
  - pip install --no-cache-dir pipenv yapf
  - cd backend
  - pipenv install --python 3.8
  - pipenv run python manage.py test
  - yapf --diff -r . || echo 'Not formatted correctly'

test-frontend:
  stage: test
  image: node
  script:
    - cd frontend
    - yarn install
    - CI=true yarn test
    - node_modules/.bin/standard

#staging:
#  stage: deploy
#  script:
#  - apk add --update ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=9b611be7-370f-4e93-925c-16b4ccf3b579
#  only:
#  - master

#
#production:
#  stage: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
