stages:
  - test
  - deploy

test-backend:
  image: python:3.8-alpine
  stage: test
  script:
  - pip install --no-cache-dir pipenv yapf
  - cd backend
  - pipenv install --python 3.8
  - pipenv run python manage.py test
  - yapf --diff -r . || echo 'Not formatted correctly'

test-frontend:
  stage: test
  image: node
  script:
    - cd frontend
    - yarn install
    - CI=true yarn test
    - node_modules/.bin/standard

staging:
  stage: deploy
  image: ruby:alpine
  script:
  - apk add --update ruby-dev curl git git-subtree
  - gem install dpl --pre
  - rm -r frontend
  - git subtree split --prefix backend > .git/refs/heads/split
  - git checkout -f split 
  - echo $SECRET_HEROKU_API_KEY
  - dpl --provider=heroku --app=pu65-api-staging --api-key=$SECRET_HEROKU_API_KEY
  environment:
      name: staging
      url: https://pu65-api-staging.herokuapp.com
  only:
    - develop

production:
  stage: deploy
  image: ruby:alpine
  script:
  - apk add --update ruby-dev curl git git-subtree
  - gem install dpl --pre
  - rm -r frontend
  - git subtree split --prefix backend > .git/refs/heads/split
  - git checkout -f split 
  - dpl --provider=heroku --app=pu65-api --api-key=$SECRET_HEROKU_API_KEY
  environment:
      name: staging
      url: https://pu65-api.herokuapp.com
  only:
    - master

