export const COLLECTION = {
  FETCH_PENDING: 'COLLECTION_FETCH_PENDING',
  FETCH_SUCCESS: 'COLLECTION_FETCH_SUCCESS',
  FETCH_ERROR: 'COLLECTION_FETCH_ERROR',

  CREATE_PENDING: 'COLLECTION_CREATE_PENDING',
  CREATE_SUCCESS: 'COLLECTION_CREATE_SUCCESS',
  CREATE_ERROR: 'COLLECTION_CREATE_ERROR',

  ADD_ITEM_PENDING: 'ADD_ITEM_PENDING',
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  ADD_ITEM_ERROR: 'ADD_ITEM_ERROR',

  UPDATE_ITEM_PENDING: 'UPDATE_ITEM_PENDING',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM_ERROR'
}

export const WORKSPACE = {
  CREATE_PENDING: 'WORKSPACE_CREATE_PENDING',
  CREATE_SUCCESS: 'WORKSPACE_CREATE_SUCCESS',
  CREATE_ERROR: 'WORKSPACE_CREATE_ERROR',

  FETCH_PENDING: 'WORKSPACE_FETCH_PENDING',
  FETCH_SUCCESS: 'WORKSPACE_FETCH_SUCCESS',
  FETCH_ERROR: 'WORKSPACE_FETCH_ERROR'
}

export const AUTH = {
  LOG_IN_PENDING: 'LOG_IN_PENDING',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_ERROR: 'LOG_IN_ERROR',

  // NOT IMPLEMENTED
  LOG_OUT: 'LOG_OUT',
  CREATE_USER: 'CREATE_USER'
}

export const MEMBERS = {
  FETCH_PENDING: 'MEMBERS_FETCH_PENDING',
  FETCH_SUCCESS: 'MEMBERS_FETCH_SUCCESS',
  FETCH_ERROR: 'MEMBERS_FETCH_ERROR',

  ADD_MEMBER_WORKSPACE: 'MEMBER_ADD_MEMBER_WORKSPACE',
  ADD_MEMBER_COLLECTION: 'MEMBER_ADD_MEMBER_COLLECTION'
}
