# Generated by Django 3.0.2 on 2020-02-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200202_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='app.Collection'),
        ),
    ]
