# Generated by Django 3.0.2 on 2020-02-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200211_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='app.Workspace'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added', to='app.Member'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='bought_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought', to='app.Member'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='part_of_workspaces', to='app.Member'),
        ),
    ]
