# Generated by Django 3.0.3 on 2020-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200212_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='name',
            field=models.TextField(
                max_length=128, verbose_name='the text to show in the list'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'name')},
        ),
    ]
