# Generated by Django 3.0.3 on 2020-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200302_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(related_name='joined_collections',
                                         to='app.Member'),
        ),
    ]
